In [1]:
import pickle
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

pd.set_option("display.max_rows", None)   # Muestra todas las filas
pd.set_option("display.max_columns", None)  # Muestra todas las columnas
pd.set_option("display.width", None)     # No corta la tabla en varias líneas
pd.set_option("display.max_colwidth", None)  # Muestra el contenido de celdas completo

In [2]:
with open("../data/join/df_data.pk1", "rb") as f:
    df_data = pickle.load(f)

In [3]:
df_data.dtypes

started_at                 datetime64[ns]
ride_id                            object
rideable_type                      object
ended_at                   datetime64[ns]
member_casual                      object
year                                int64
month                               int64
day                                 int64
time_hms_ms               timedelta64[ns]
day_type                           object
event                                bool
start_station_id                   object
end_station_id                     object
temperature                       float64
wind_speed                        float64
precipitation                     float64
relative_humidity                 float64
snow_depth                        float64
station_level_pressure            float64
dtype: object

In [4]:
df_data.head(10)

,started_at,ride_id,rideable_type,ended_at,member_casual,year,month,day,time_hms_ms,day_type,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,station_level_pressure
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,classic_bike,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,Normal,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,1004.100000
1,2022-01-04 11:26:49,03A4B2FF57D83F87,classic_bike,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,Normal,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,1001.100000
2,2022-01-04 13:13:55,656B583500F94041,classic_bike,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,Normal,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,1000.278333
3,2022-01-12 15:29:54,E1E90907D0DAAD57,electric_bike,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,Normal,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,995.800000
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,classic_bike,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,Weekend,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,1000.840000
5,2022-01-19 01:24:31,B0F671970D931958,electric_bike,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,Normal,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,985.533333
6,2022-01-19 20:27:40,3176B3813FE0A70F,classic_bike,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,Normal,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,999.201667
7,2022-01-22 15:50:57,6BC5C606225A8E2A,electric_bike,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,Weekend,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,1002.030000
8,2022-01-27 16:55:40,7357060865A428A7,classic_bike,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,Normal,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,998.026667
9,2022-01-30 17:46:42,2A296A2202DCF568,electric_bike,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,Weekend,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,993.100000

# Como se ha menciodando se elimina la columna de presión atomosférica

In [5]:
df_data = df_data.drop(columns=["station_level_pressure"])

# Se realiza el One-Hot Encoding

## De rideable_type

In [6]:
df_data['rideable_type'].unique()

array(['classic_bike', 'electric_bike', 'docked_bike'], dtype=object)

In [7]:
df_data = pd.get_dummies(df_data, columns=['rideable_type'], prefix=['rideable_type'])

In [8]:
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,day_type,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,Normal,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,Normal,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,Normal,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,Normal,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,Weekend,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,Normal,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,Normal,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,Weekend,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,Normal,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,Weekend,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True

## De member casul

In [9]:
df_data['member_casual'].unique()

array(['casual', 'member'], dtype=object)

In [10]:
df_data["member_casual_bool"] = df_data["member_casual"].map({
    "member": False,
    "casual": True
})

In [11]:
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,day_type,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,Normal,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,Normal,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,Normal,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,Normal,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,Weekend,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,Normal,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,Normal,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,Weekend,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,Normal,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,Weekend,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True

## De day_type

In [12]:
df_data['day_type'].unique()

array(['Normal', 'Weekend', 'Holiday'], dtype=object)

In [13]:
df_data = pd.get_dummies(df_data, columns=['day_type'], prefix=['day_type'])

In [14]:
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True

# Normalizacion de variables numéricas

Se usa una estandarización centrada en 0

## Temperatura

In [15]:
scaler_temperature = StandardScaler()
df_data["temp_std"] = scaler_temperature.fit_transform(df_data[["temperature"]])
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661

## Wind speed

In [16]:
scaler_wind = StandardScaler()
df_data["wind_std"] = scaler_wind.fit_transform(df_data[["wind_speed"]])
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036

## Humedad relativa

Aunque ya está en un rango de 0% a 100% se elige realizar la normalizacion igualmente

In [17]:
scaler_rel_humi = StandardScaler()
df_data["rel_humidity_std"] = scaler_rel_humi.fit_transform(df_data[["relative_humidity"]])
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601

## Precipitacion

In [18]:
scaler_precipitation = StandardScaler()
df_data["precipitation_std"] = scaler_precipitation.fit_transform(df_data[["precipitation"]])
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std,precipitation_std
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001,-0.099704
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601,-0.099704
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055,-0.099704
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358,-0.099704
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432,-0.099704
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620,-0.099704
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156,-0.099704
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125,-0.099704
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943,-0.099704
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601,-0.099704

## Snow_depth

In [19]:
scaler_snow_depth = StandardScaler()
df_data["snow_depth_std"] = scaler_snow_depth.fit_transform(df_data[["snow_depth"]])
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std,precipitation_std,snow_depth_std
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001,-0.099704,-0.056148
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601,-0.099704,-0.056148
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055,-0.099704,-0.056148
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358,-0.099704,-0.056148
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432,-0.099704,-0.056148
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620,-0.099704,-0.056148
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156,-0.099704,-0.056148
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125,-0.099704,-0.056148
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943,-0.099704,-0.056148
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601,-0.099704,-0.056148

## Se guardan los scaler para su uso futuro

In [20]:
with open('../data/normalized/scalerTemperature.pkl', 'wb') as f:
    pickle.dump(scaler_temperature, f)
    
with open('../data/normalized/scalerWind.pkl', 'wb') as f:
    pickle.dump(scaler_wind, f)
    
with open('../data/normalized/scalerHumidity.pkl', 'wb') as f:
    pickle.dump(scaler_rel_humi, f)
    
with open('../data/normalized/scalerPrecipitation.pkl', 'wb') as f:
    pickle.dump(scaler_precipitation, f)
    
with open('../data/normalized/scalerSnowDepth.pkl', 'wb') as f:
    pickle.dump(scaler_snow_depth, f)

# Normalización de las estaciones de inicio y fin

In [23]:
from sklearn.preprocessing import LabelEncoder

with open("../data/bicycles/le_station_encoder.pkl", "rb") as f:
    le_station = pickle.load(f)
    
df_data["start_station_idx"] = le_station.transform(df_data["start_station_id"])
df_data["end_station_idx"]   = le_station.transform(df_data["end_station_id"])

In [59]:
# Se observan las etiquetas
le_station.classes_

array(['03a1610c-3ba0-4b85-b512-bc26791cb7ee',
       '080ab938-2c1b-4fcf-a83d-74c5ae6ff305',
       '0eeb6baf-c653-4a1a-af17-99f686116b89', ...,
       'ee925757-31ce-41ad-9bb7-73b1bb363616',
       'f0f9f5dc-3d3f-4a32-aa3e-b87566e44de9',
       'ff21c158-de98-46c6-9ef7-7082bdb7c634'],
      shape=(1675,), dtype=object)

In [25]:
# Se observa una de las estaciones
le_station.transform(["a3a44476-a135-11e9-9cda-0a87ae2ba916"])[0]

np.int64(1331)

## Se guarda el LabelEncoder para traducir los datos en el futuro

In [26]:
with open('../data/normalized/le_station_encoder.pkl', 'wb') as f:
    pickle.dump(le_station, f)

In [27]:
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std,precipitation_std,snow_depth_std,start_station_idx,end_station_idx
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001,-0.099704,-0.056148,1281,1896
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601,-0.099704,-0.056148,1819,1645
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055,-0.099704,-0.056148,1250,1250
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358,-0.099704,-0.056148,1896,1911
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432,-0.099704,-0.056148,1893,1646
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620,-0.099704,-0.056148,1820,1820
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156,-0.099704,-0.056148,1893,1820
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125,-0.099704,-0.056148,1267,1267
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943,-0.099704,-0.056148,1080,1080
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601,-0.099704,-0.056148,1896,1896

# Se convierte la columna de hora y mes a variables cíclicas para que el modelo pueda extraer mejor las características

In [28]:
# Se obtiene la hora en formato 0-23
# df_data["hour"] = pd.to_timedelta(df_data["time_hms_ms"])  # ejemplo

# Convertir timedelta a número de horas (float)
df_data["hour_float"] = df_data["time_hms_ms"].dt.total_seconds() / 3600

df_data["hour_sin"] = np.sin(2 * np.pi * df_data["hour_float"] / 24)
df_data["hour_cos"] = np.cos(2 * np.pi * df_data["hour_float"] / 24)

In [29]:
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std,precipitation_std,snow_depth_std,start_station_idx,end_station_idx,hour_float,hour_sin,hour_cos
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001,-0.099704,-0.056148,1281,1896,4.641111,0.937383,0.348299
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601,-0.099704,-0.056148,1819,1645,11.446944,0.144284,-0.989536
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055,-0.099704,-0.056148,1250,1250,13.231944,-0.316960,-0.948439
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358,-0.099704,-0.056148,1896,1911,15.498333,-0.793088,-0.609108
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432,-0.099704,-0.056148,1893,1646,8.467778,0.798460,-0.602047
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620,-0.099704,-0.056148,1820,1820,1.408611,0.360472,0.932770
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156,-0.099704,-0.056148,1893,1820,20.461111,-0.799510,0.600653
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125,-0.099704,-0.056148,1267,1267,15.849167,-0.845611,-0.533799
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943,-0.099704,-0.056148,1080,1080,16.927778,-0.960860,-0.277035
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601,-0.099704,-0.056148,1896,1896,17.778333,-0.998317,-0.058000

# Se convierte la variable month a una variable ciclica

In [30]:
df_data["month_sin"] = np.sin(2 * np.pi * df_data["month"] / 12)
df_data["month_cos"] = np.cos(2 * np.pi * df_data["month"] / 12)

In [31]:
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std,precipitation_std,snow_depth_std,start_station_idx,end_station_idx,hour_float,hour_sin,hour_cos,month_sin,month_cos
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001,-0.099704,-0.056148,1281,1896,4.641111,0.937383,0.348299,0.5,0.866025
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601,-0.099704,-0.056148,1819,1645,11.446944,0.144284,-0.989536,0.5,0.866025
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055,-0.099704,-0.056148,1250,1250,13.231944,-0.316960,-0.948439,0.5,0.866025
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358,-0.099704,-0.056148,1896,1911,15.498333,-0.793088,-0.609108,0.5,0.866025
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432,-0.099704,-0.056148,1893,1646,8.467778,0.798460,-0.602047,0.5,0.866025
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620,-0.099704,-0.056148,1820,1820,1.408611,0.360472,0.932770,0.5,0.866025
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156,-0.099704,-0.056148,1893,1820,20.461111,-0.799510,0.600653,0.5,0.866025
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125,-0.099704,-0.056148,1267,1267,15.849167,-0.845611,-0.533799,0.5,0.866025
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943,-0.099704,-0.056148,1080,1080,16.927778,-0.960860,-0.277035,0.5,0.866025
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601,-0.099704,-0.056148,1896,1896,17.778333,-0.998317,-0.058000,0.5,0.866025

# Se añade una columna que contabilice la duración de cada viaje

In [32]:
# Duración en minutos
df_data['duration_min'] = (df_data['ended_at'] - df_data['started_at']).dt.total_seconds() / 60

In [33]:
df_data.head(10)

,started_at,ride_id,ended_at,member_casual,year,month,day,time_hms_ms,event,start_station_id,end_station_id,temperature,wind_speed,precipitation,relative_humidity,snow_depth,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std,precipitation_std,snow_depth_std,start_station_idx,end_station_idx,hour_float,hour_sin,hour_cos,month_sin,month_cos,duration_min
0,2022-01-04 04:38:28,12E6E4CC93D5FDBB,2022-01-04 04:51:48,casual,2022,1,4,0 days 04:38:28,False,8fd03909-317e-4b6c-b8e9-f4c28b4c90b1,bbb67562-1f82-4dfa-a532-231ddc35444e,-5.47,3.100000,0.0,74.85,0.0,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001,-0.099704,-0.056148,1281,1896,4.641111,0.937383,0.348299,0.5,0.866025,13.333333
1,2022-01-04 11:26:49,03A4B2FF57D83F87,2022-01-04 11:35:30,casual,2022,1,4,0 days 11:26:49,False,a3b2905a-a135-11e9-9cda-0a87ae2ba916,a3ad09b2-a135-11e9-9cda-0a87ae2ba916,-5.00,4.600000,0.0,80.00,0.0,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601,-0.099704,-0.056148,1819,1645,11.446944,0.144284,-0.989536,0.5,0.866025,8.683333
2,2022-01-04 13:13:55,656B583500F94041,2022-01-04 13:52:27,member,2022,1,4,0 days 13:13:55,False,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,2a80f8d9-85dc-4c36-ba07-86d775ffd1ee,-5.00,4.841667,0.0,82.90,0.0,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055,-0.099704,-0.056148,1250,1250,13.231944,-0.316960,-0.948439,0.5,0.866025,38.533333
3,2022-01-12 15:29:54,E1E90907D0DAAD57,2022-01-12 15:36:05,casual,2022,1,12,0 days 15:29:54,False,bbb67562-1f82-4dfa-a532-231ddc35444e,ff21c158-de98-46c6-9ef7-7082bdb7c634,0.75,2.850000,0.0,76.25,0.0,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358,-0.099704,-0.056148,1896,1911,15.498333,-0.793088,-0.609108,0.5,0.866025,6.183333
4,2022-01-16 08:28:04,8CDE4F5C9F79729C,2022-01-16 08:58:12,casual,2022,1,16,0 days 08:28:04,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3ad0ecb-a135-11e9-9cda-0a87ae2ba916,-9.83,1.885000,0.0,74.30,0.0,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432,-0.099704,-0.056148,1893,1646,8.467778,0.798460,-0.602047,0.5,0.866025,30.133333
5,2022-01-19 01:24:31,B0F671970D931958,2022-01-19 02:20:34,casual,2022,1,19,0 days 01:24:31,False,a3b2956a-a135-11e9-9cda-0a87ae2ba916,a3b2956a-a135-11e9-9cda-0a87ae2ba916,5.00,6.033333,0.0,70.00,0.0,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620,-0.099704,-0.056148,1820,1820,1.408611,0.360472,0.932770,0.5,0.866025,56.050000
6,2022-01-19 20:27:40,3176B3813FE0A70F,2022-01-19 20:37:50,member,2022,1,19,0 days 20:27:40,False,b09832de-1c8e-4b92-bd72-bd98dc80b92c,a3b2956a-a135-11e9-9cda-0a87ae2ba916,-5.00,6.483333,0.0,58.00,0.0,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156,-0.099704,-0.056148,1893,1820,20.461111,-0.799510,0.600653,0.5,0.866025,10.166667
7,2022-01-22 15:50:57,6BC5C606225A8E2A,2022-01-22 16:36:41,casual,2022,1,22,0 days 15:50:57,False,6849c4e2-cffa-432b-8d83-5c0524594b4f,6849c4e2-cffa-432b-8d83-5c0524594b4f,-4.90,5.020000,0.0,67.50,0.0,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125,-0.099704,-0.056148,1267,1267,15.849167,-0.845611,-0.533799,0.5,0.866025,45.733333
8,2022-01-27 16:55:40,7357060865A428A7,2022-01-27 17:24:18,member,2022,1,27,0 days 16:55:40,False,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,1e7e4cf3-a16b-4cb7-9ead-fdd71e07ea77,0.00,9.255000,0.0,51.00,0.0,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943,-0.099704,-0.056148,1080,1080,16.927778,-0.960860,-0.277035,0.5,0.866025,28.633333
9,2022-01-30 17:46:42,2A296A2202DCF568,2022-01-30 17:52:22,casual,2022,1,30,0 days 17:46:42,False,bbb67562-1f82-4dfa-a532-231ddc35444e,bbb67562-1f82-4dfa-a532-231ddc35444e,-2.00,4.600000,0.0,80.00,0.0,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601,-0.099704,-0.056148,1896,1896,17.778333,-0.998317,-0.058000,0.5,0.866025,5.666667

# Se guardan los datos

In [34]:
df_data.to_pickle("../data/normalized/df_normalized.pk1")

# Se limpian las columnas que no van a ser usadas durante el entrenamiento del modelo

In [35]:
df_model = df_data.drop(columns=[
    "ride_id",
    "started_at",
    "ended_at",
    "start_station_id",
    "end_station_id",
    "member_casual",
    "month",
    "day", # Se va a usar day_type desglosado en dummies
    "time_hms_ms",
    "temperature",
    "wind_speed",
    "relative_humidity",
    "precipitation",
    "snow_depth"
])

In [36]:
df_model.head(10)

,year,event,rideable_type_classic_bike,rideable_type_docked_bike,rideable_type_electric_bike,member_casual_bool,day_type_Holiday,day_type_Normal,day_type_Weekend,temp_std,wind_std,rel_humidity_std,precipitation_std,snow_depth_std,start_station_idx,end_station_idx,hour_float,hour_sin,hour_cos,month_sin,month_cos,duration_min
0,2022,False,True,False,False,True,False,True,False,-2.348318,-0.573362,0.916001,-0.099704,-0.056148,1281,1896,4.641111,0.937383,0.348299,0.5,0.866025,13.333333
1,2022,False,True,False,False,True,False,True,False,-2.299739,0.115036,1.211601,-0.099704,-0.056148,1819,1645,11.446944,0.144284,-0.989536,0.5,0.866025,8.683333
2,2022,False,True,False,False,False,False,True,False,-2.299739,0.225945,1.378055,-0.099704,-0.056148,1250,1250,13.231944,-0.316960,-0.948439,0.5,0.866025,38.533333
3,2022,False,False,False,True,True,False,True,False,-1.705422,-0.688095,0.996358,-0.099704,-0.056148,1896,1911,15.498333,-0.793088,-0.609108,0.5,0.866025,6.183333
4,2022,False,True,False,False,True,False,False,True,-2.798966,-1.130964,0.884432,-0.099704,-0.056148,1893,1646,8.467778,0.798460,-0.602047,0.5,0.866025,30.133333
5,2022,False,False,False,True,True,False,True,False,-1.266144,0.772839,0.637620,-0.099704,-0.056148,1820,1820,1.408611,0.360472,0.932770,0.5,0.866025,56.050000
6,2022,False,True,False,False,False,False,True,False,-2.299739,0.979358,-0.051156,-0.099704,-0.056148,1893,1820,20.461111,-0.799510,0.600653,0.5,0.866025,10.166667
7,2022,False,False,False,True,True,False,False,True,-2.289403,0.307788,0.494125,-0.099704,-0.056148,1267,1267,15.849167,-0.845611,-0.533799,0.5,0.866025,45.733333
8,2022,False,True,False,False,False,False,True,False,-1.782942,2.251365,-0.452943,-0.099704,-0.056148,1080,1080,16.927778,-0.960860,-0.277035,0.5,0.866025,28.633333
9,2022,False,False,False,True,True,False,False,True,-1.989661,0.115036,1.211601,-0.099704,-0.056148,1896,1896,17.778333,-0.998317,-0.058000,0.5,0.866025,5.666667

In [37]:
df_model.dtypes

year                             int64
event                             bool
rideable_type_classic_bike        bool
rideable_type_docked_bike         bool
rideable_type_electric_bike       bool
member_casual_bool                bool
day_type_Holiday                  bool
day_type_Normal                   bool
day_type_Weekend                  bool
temp_std                       float64
wind_std                       float64
rel_humidity_std               float64
precipitation_std              float64
snow_depth_std                 float64
start_station_idx                int64
end_station_idx                  int64
hour_float                     float64
hour_sin                       float64
hour_cos                       float64
month_sin                      float64
month_cos                      float64
duration_min                   float64
dtype: object